Creation Of View Pages - Blog App Project
ouasamine/rails-blog pull request #6
Opened 2023-01-25 20:39 UTC by ouasamine

## Overview
In this part, I fetched data from the database and displayed it on the view pages.

## Workflow

- [Fetched all users' details and displayed them on the respective view page](https://github.com/ouasamine/rails-blog/commit/ac2be075963b9279cdfd324433e6ca91d97d1815)
- [Fetched details of a single user and displayed them on the respective view page](https://github.com/ouasamine/rails-blog/commit/9a99b8fc95f7732fc681135866e694ebcf880ed4)
- [Fetched posts' details of a given user and displayed them on the respective view page](https://github.com/ouasamine/rails-blog/commit/cf1978c1265f53acf10c617fa8ef3f985154ee5c)
- [Fetched a single post details and displayed them on the respective view page](https://github.com/ouasamine/rails-blog/commit/14375fab433e1669039e2a4e21b4b1509b0ed7b8)
- [Structred the view pages with HTML tags](https://github.com/ouasamine/rails-blog/commit/221c8cb8fc4fdc972288fd2b33c520af85926c4e)
- [Styled all view pages](https://github.com/ouasamine/rails-blog/commit/4be23fca32fa8da69147124270172a59d4ec3013)

2023-01-25 21:08 UTC, AnselemOdims requested changes
### Hi @ouasamine , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-25 21:08 UTC, AnselemOdims commented on app/views/users/index.html.erb
> +<% end %>
- [ ] Good job on this , but when a user is clicked it should navigate to the show page which is not happening at the moment.

2023-01-25 21:14 UTC, ouasamine commented on app/views/users/index.html.erb
> +<% end %>
Working on that @AnselemOdims, thank you 👍🏽

2023-01-26 14:12 UTC, danmainah approved these changes
Hi @ouasamine , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️ No linter errors
✔️ Gitflow was correctly used
✔️  Good design

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-26 14:12 UTC, danmainah commented on app/views/users/show.html.erb
> +</div>
- [ ] [optional] It would be nice if you added a **See all Post** links opening user's post index as displayed on the [wireframe](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_user_all_posts.png)

2023-01-26 14:16 UTC, ouasamine commented on app/views/users/show.html.erb
> +</div>
Noted, thank you @danmainah 👍🏽

2023-01-26 14:25 UTC, merged